### ISSUE TITLE
Where can I get examples of HPP problem?

### ISSUE THREAD

**Issue by loster-1** [c4v4/LKH3#1]
Where can I get examples of HPP problem?

**Comment by c4v4** [comment]
Hi! 
I would suggest you refer directly to the [original project](http://webhotel4.ruc.dk/~keld/research/LKH/) maintained by Keld Helsgaun. 
I didn't work with the HPP thus, there is no real advantage to using this version instead of the original.

If performance is key, I would suggest directly using LKH-2 (instead of the more generic [LKH-3](http://webhotel4.ruc.dk/~keld/research/LKH-3/)), which for my limited experience is slightly faster.

As far as I know, there are no examples available for the HPP, so I think your best option is to look for examples of other problems and adapt them accordingly (note that the algorithm expects instances in the TSPLIB format).
